# -*- coding: utf-8 -*-
"""OIMAC_params.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pblgvr7gcLFudfJrLWZ9qAsAjz2LsJyi
"""

critic_params_1 = {
    'dim': 1,
    'layers': 4,
    'embed_dim': 32,
    'hidden_dim': 64,
    'activation': 'relu',
    'ref_batch_factor': 10,
    'learning_rate': 0.0001
}

nit_params_1 = {'dim': 1,
              'layers': 5,
              'hidden_dim': 128,
              'activation': 'relu',
              'tx_power': 1.0,
              'learning_rate': 0.0001,
              'peak_amp': np.power(10,5/10) }
critic_params_2 = {
    'dim': 1,
    'layers': 4,
    'embed_dim': 32,
    'hidden_dim': 64,
    'activation': 'relu',
    'ref_batch_factor': 10,
    'learning_rate': 0.0001
}

nit_params_2 = {'dim': 1,
              'layers': 5,
              'hidden_dim': 128,
              'activation': 'relu',
              'tx_power': 1.0,
              'learning_rate': 0.0001,
              'peak_amp': np.power(10,1) }